hugobengtsson/Projektarbete-Webbshop

components/footer.js, components/navbar.js, components/productCard.js, css/common.css, css/mediaQueries.css, css/navbar.css, css/productCard.css, index.php, swiper.js
Started with the product page layout!
#6
=> Fixing frontend for product page

components/navbar.js, components/productCard.js, css/common.css, css/navbar.css, css/productCard.css, css/startpage.css, landing.html
=> styling product page and created landing file

components/footer.js, components/navbar.js, components/productCard.js, css/common.css, css/mediaQueries.css, css/navbar.css, css/productCard.css
changed font, made picture bigger, fixed media queries and background color
=> styled the product page and resized boxes

api/classes/createInstanceFunctions.php, api/classes/databaseClass.php, api/classes/imageClass.php, api/classes/productClass.php, api/classes/sizeClass.php, api/controllers/imageController.php, api/controllers/mainController.php, api/controllers/productController.php, api/controllers/sizeController.php, api/receivers/productReceiver.php
#23 
Fetching all products, images and sizes. Adds the data together to one object that has all information for rendering on the product page.
=> Logic for fetching all products.

api/classes/categoryClass.php, api/classes/createInstanceFunctions.php, api/classes/databaseClass.php, api/controllers/categoryController.php, api/receivers/categoryReciever.php, api/receivers/productReceiver.php, js/main.js
#36 - Fetching all categories and fetching category by ID.
#9 - Fetching all products with relation to one category. Fetching by category ID.
=> PHP for fetching categories.

admin.html, api/classes/databaseClass.php, api/controllers/productController.php, api/receivers/productReceiver.php, css/adminPage.css, js/main.js, js/uploadProduct.js
=> initial push adminpage

api/classes/createInstanceFunctions.php, api/classes/databaseClass.php, api/classes/imageClass.php, api/classes/productClass.php, api/classes/sizeClass.php, api/controllers/imageController.php, api/controllers/productController.php, api/controllers/sizeController.php, api/receivers/productReceiver.php, js/uploadProduct.js
#40 
#62 
Logic and SQL for uploading product, sizes with inputed stock and image src to database. 
Left to do with this functionality is to render categories to the component and to make the functionality for choosing one or multiple categories when creating the product. 
Also add return message to user and reload the forms so that it does not get entered multiple times bu misstake.
=> Added functionality to add product.

api/controllers/productController.php, api/receivers/productReceiver.php, js/main.js
=> logic and backend for fetching product by ID

cartpage.html, components/navbar.js, components/productCardRender.js, css/navbar.css, js/cartpage.js
fixed navbar dilema
fixed price div + rendering
=> fixed carpae rendering and some small stuff

admin.html, api/classes/databaseClass.php, api/classes/newsletterClass.php, api/controllers/newsletterController.php, api/controllers/productController.php, api/receivers/newsletterReceiver.php, css/adminPage.css, js/adminpage.js, js/uploadProduct.js
#50 #53 working newsletter logic and adding newsletter to database
=> added newsletter logic

css/myPages.css, js/main.js, js/myPages.js, myPages.html
#59  also commented out the eventlisteners on main.js
=> Added myPages

api/classes/databaseClass.php, api/classes/subscriberClass.php, api/controllers/newsletterController.php, api/receivers/subscriberReceiver.php, components/footer.js, css/productCard.css, product.html
#52 + additional changes (see title)
=> added newsletter subscription logic and  field + footer component

api/controllers/cartController.php, api/receivers/cartReciever.php, components/productCardRender.js, css/productCard.css, js/main.js
=> Functionality to add items to cart with session.

components/productCardRender.js
Modified what saves to session storage as cart items.
=> Modified the save to session storage

api/controllers/cartController.php, api/receivers/cartReciever.php, components/productCardRender.js, js/cartpage.js
=> Adding logic to quantity buttons on cart page

api/classes/createInstanceFunctions.php, api/classes/databaseClass.php, api/classes/freightClass.php, api/controllers/freightController.php, api/receivers/freightReciever.php, css/cartpage.css, js/cartpage.js
=> front end for freight options

api/classes/createInstanceFunctions.php, api/classes/orderClass.php, api/controllers/orderController.php, api/controllers/orderDetailsController.php, api/receivers/orderReciever.php, js/cartpage.js
#106 
Still left to do: 
Remove from session storage. (Having issues with removing the key from session)
Render out message that the order is placed to user.
=> Adding logic for placing order

api/classes/databaseClass.php, api/controllers/adminRequestController.php, api/controllers/orderController.php, api/receivers/adminRequestReceiver.php, api/receivers/orderReciever.php, components/navbar.js, css/myPages.css, js/myPages.js
adminrequest button functions etc
=> adminrequest button functions etc

admin.html, api/controllers/productController.php, api/receivers/productReceiver.php, js/adminpage.js, js/main.js, js/removeProduct.js
#48 
#118 
Still needs to reload the div or page after delete and change of products.
=> logic for updating stock and removing products

components/navbar.js, css/index.css, css/mediaQueries.css, css/myPages.css, css/navbar.css, index.html, js/cartpage.js, js/index.js, myPages.html
fixed denied access to checkout if not logged in, fixed the dropdown buttons to more" secure", half fixed navbar hamburger. #58
=> fixed index responsive, checkout button,

components/navbar.js, css/index.css, css/mediaQueries.css, css/myPages.css, css/navbar.css, index.html, js/cartpage.js, js/index.js, myPages.html
Reverts hugobengtsson/Projektarbete-Webbshop#130
=> Revert "fixed index responsive, checkout button,"

components/navbar.js, css/cartpage.css, css/navbar.css, myPages.html
=> Responsive2

js/cartpage.js
forgot to inject this bitch into my last commit sorry ... lolz
=> mini push och please log in before check out

js/myPages.js
bugfixes for rendering on myPages!
=> bug fixes on myPages

admin.html, api/controllers/orderController.php, api/receivers/categoryReciever.php, api/receivers/orderReciever.php, css/adminPage.css, js/adminpage.js, js/myPages.js
added button to change order status
=> added functionality admin page order status

api/receivers/productReceiver.php, js/uploadProduct.js
=> fixed small issue with uploadProduct on admin page

admin.html, api/classes/databaseClass.php, api/controllers/adminRequestController.php, api/controllers/userController.php, api/receivers/adminRequestReceiver.php, api/receivers/test.php, components/navbar.js, css/adminPage.css, css/myPages.css, js/adminpage.js, js/myPages.js
accept admin request functions and some CSS fixes to myPages
=> accept admin request functions and some CSS fixes to myPages

api/controllers/orderController.php, components/navbar.js, css/adminPage.css, css/myPages.css, css/navbar.css, js/adminpage.js, js/cartpage.js, js/myPages.js
=> fixed cart number icon and small fixes

api/receivers/categoryReciever.php, api/receivers/newsletterReceiver.php, api/receivers/orderReciever.php, api/receivers/productReceiver.php, css/index.css, js/adminpage.js, js/index.js
#125 - i only blocking endpoints for adminpage 
and fixed the rendering in index page
=> Fixed rendering for Indexpage and blocking endpoints for Admin page

css/myPages.css, js/myPages.js, myPages.html
Some fixes to myPages to make it look better.
=> some fixes to myPages

components/navbar.js
=> Fixed indentation in navbar templet strings?

css/mediaQueries.css, css/myPages.css, js/myPages.js, myPages.html
=> responsivness for myPages

components/navbar.js, css/mediaQueries.css, css/navbar.css
=> fixed some bullshit 💩💩

css/mediaQueries.css, css/navbar.css
=> bull shit part 2 💩💩💩
